import { describe, expect, it } from "vitest";
import { buildDetailedBreakdowns } from "../detailedBreakdown";

function makeCommit(overrides: Partial<Record<string, unknown>> = {}) {
  return {
    _id: "test" as never,
    _creationTime: Date.now(),
    repoId: "repo" as never,
    sha: "sha",
    message: "test",
    authoredAt: Date.now(),
    committedAt: Date.now(),
    classification: "human",
    ...overrides,
  };
}

describe("buildDetailedBreakdowns", () => {
  it("keeps specific AI tools as explicit entries", () => {
    const { toolBreakdown } = buildDetailedBreakdowns([
      makeCommit({ classification: "copilot", additions: 12 }),
    ] as never);

    expect(toolBreakdown).toEqual([
      { key: "github-copilot", label: "GitHub Copilot", commits: 1, additions: 12 },
    ]);
  });

  it("splits ai-assisted commits into concrete tools when detectable", () => {
    const { toolBreakdown } = buildDetailedBreakdowns([
      makeCommit({
        classification: "ai-assisted",
        authorLogin: "coderabbitai[bot]",
        additions: 3,
      }),
      makeCommit({
        classification: "ai-assisted",
        message: "Generated by Qodo",
        additions: 5,
      }),
    ] as never);

    expect(toolBreakdown).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ key: "coderabbit", commits: 1 }),
        expect.objectContaining({ key: "qodo-merge", commits: 1 }),
      ])
    );
  });

  it("splits other-bot commits into concrete bots when detectable", () => {
    const { botBreakdown } = buildDetailedBreakdowns([
      makeCommit({ classification: "other-bot", authorLogin: "codecov[bot]" }),
      makeCommit({ classification: "other-bot", authorLogin: "mergify[bot]" }),
    ] as never);

    expect(botBreakdown).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ key: "codecov", commits: 1 }),
        expect.objectContaining({ key: "mergify", commits: 1 }),
      ])
    );
  });

  it("falls back to explicit per-identity labels instead of grouping as others", () => {
    const { botBreakdown } = buildDetailedBreakdowns([
      makeCommit({ classification: "other-bot", authorLogin: "internal-helper-bot[bot]" }),
    ] as never);

    expect(botBreakdown).toEqual([
      expect.objectContaining({
        key: "bot-internal-helper-bot",
        label: "Internal Helper Bot",
        commits: 1,
      }),
    ]);
  });

  it("maps v1 bot identity to Vercel Bot", () => {
    const { botBreakdown } = buildDetailedBreakdowns([
      makeCommit({ classification: "other-bot", authorLogin: "v1[bot]" }),
    ] as never);

    expect(botBreakdown).toEqual([
      expect.objectContaining({
        key: "vercel",
        label: "Vercel Bot",
        commits: 1,
      }),
    ]);
  });

  it("uses explicit unknown labels when no strong signal is found", () => {
    const { toolBreakdown, botBreakdown } = buildDetailedBreakdowns([
      makeCommit({ classification: "ai-assisted", coAuthors: ["Jane <jane@example.com>"] }),
      makeCommit({ classification: "other-bot", authorLogin: "" }),
    ] as never);

    expect(toolBreakdown).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ key: "ai-unspecified", label: "Unknown AI Assistant" }),
      ])
    );
    expect(botBreakdown).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ key: "bot-unspecified", label: "Unknown Automation Bot" }),
      ])
    );
  });
});
